app:
  name: "MusicStreamingApp"
  http:
    host: "127.0.0.1"
    port: 8000
  server:
    cors:
      allow_origins: "*"
  auth:
    secret: "secret-key"
    duration: 2d
database:
  dsn: "host=127.0.0.1 user=postgres password=admin dbname=postgres port=5432 sslmode=disable"
smtp:
  host: ""
  port: 0
  password: ""
  from: ""
minio:
  endpoint: 127.0.0.1:9000
  access_key: "kGUva6PjabiSsCcLd4Fr"
  secret_key: "IO9MlxjtoPk1sjljqY2hoY6stBseMRRSsCRBlyOP"
